In [183]:
import pandas as pd
url = f'https://docs.google.com/spreadsheet/ccc?key=1T3iyoPQdI1FlJrhr-l-YjK-NlED_JfyjT7lGezZN1rY&output=csv'

In [184]:
X=pd.read_csv(url,",")

In [185]:
X

Date   Time  Carbs  Proten  Fat  Fiber  BPUpper  BPLower  \
0   12/21/2021  10:30    100      20   80     12      120       80   
1   12/22/2021  11:30    100      20   80     12      120       80   
2   12/23/2021  12:30    100      20   80     12      120       80   
3   12/24/2021  13:30    100      20   80     12      120       80   
4   12/25/2021  14:30    100      20   80     12      120       80   
5   12/26/2021  15:30    100      20   80     12      120       80   
6   12/27/2021  16:30    100      20   80     12      120       80   
7   12/28/2021  17:30    100      20   80     12      120       80   
8   12/29/2021  18:30    100      20   80     12      120       80   
9   12/30/2021  19:30    100      20   80     12      120       80   
10  12/31/2021  20:30    100      20   80     12      120       80   
11    1/1/2022  21:30    100      20   80     12      120       80   
12    1/2/2022  22:30    100      20   80     12      120       80   
13    1/3/2022  23:30    100      20   80     12      120       80   
14    1/4/2022   0:30    100      20   80     12      120       80   
15    1/5/2022   1:30    100      20   80     12      120       80   
16    1/6/2022   2:30    100      20   80     12      120       80   
17    1/7/2022   3:30    100      20   80     12      120       80   
18    1/8/2022   4:30    100      20   80     12      120       80   
19    1/9/2022   5:30    100      20   80     12      120       80   

    OxygenLevel  Weight  Water  Activity  PreviousGlucoseLevel  Medication  \
0            95     103      5       300                   110           1   
1            95     103      5       300                   110           1   
2            95     103      5       300                   110           1   
3            95     103      5       300                   110           1   
4            95     103      5       300                   110           1   
5            95     103      5       300                   110           1   
6            95     103      5       300                   110           1   
7            95     103      5       300                   110           1   
8            95     103      5       300                   110           1   
9            95     103      5       300                   110           1   
10           95     103      5       300                   110           1   
11           95     103      5       300                   110           1   
12           95     103      5       300                   110           1   
13           95     103      5       300                   110           1   
14           95     103      5       300                   110           1   
15           95     103      5       300                   110           1   
16           95     103      5       300                   110           1   
17           95     103      5       300                   110           1   
18           95     103      5       300                   110           1   
19           95     103      5       300                   110           1   

    GlucoseLevel  Prediction  
0            199         110  
1            162         110  
2            151         110  
3            120         110  
4            117         110  
5            169         110  
6            211         110  
7            281         110  
8            240         110  
9            177         110  
10           162         110  
11           295         110  
12           143         110  
13           214         110  
14           136         110  
15           234         110  
16           138         110  
17           126         110  
18           233         110  
19           106         110

In [186]:
y=X["GlucoseLevel"]

In [187]:
X = X.drop(['Date', 'Time', 'GlucoseLevel','Prediction'], axis=1)

In [188]:
y

0     199
1     162
2     151
3     120
4     117
5     169
6     211
7     281
8     240
9     177
10    162
11    295
12    143
13    214
14    136
15    234
16    138
17    126
18    233
19    106
Name: GlucoseLevel, dtype: int64

In [189]:
# split a dataset into train and test sets
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(13, 12) (7, 12) (13,) (7,)


In [190]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [191]:
reg = LinearRegression().fit(X_train, y_train)

In [192]:
reg.score(X_train, y_train)

0.0

In [193]:
reg.coef_

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [194]:
reg.intercept_

188.84615384615384

In [195]:
reg.predict(X_test)

array([188.84615385, 188.84615385, 188.84615385, 188.84615385,
       188.84615385, 188.84615385, 188.84615385])

In [196]:
reg.score(X_test, y_test)

-0.30715030078781336

In [197]:
import pickle

In [198]:
pickle.dump(reg, open('model.pkl','wb'))

In [199]:
model = pickle.load(open('model.pkl','rb'))
print(model.predict(X_test))

[188.84615385 188.84615385 188.84615385 188.84615385 188.84615385
 188.84615385 188.84615385]


In [200]:
model.predict([np.array([100, 20, 80, 12, 120, 80, 95, 103, 5, 300, 110, 1])])

array([188.84615385])